spring:
  thymeleaf:
    cache: false # ????????? ??????????? ??? ??????????
    prefix: classpath:/templates/ # ????? ? ?????????
    suffix: .html # ??????? ??????
    encoding: UTF-8 # ?????????
    mode: HTML
  config:
    import: optional:file:.env[.properties]
  application:
    name: tutor_service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8081

student:
  id: 0